### ISSUE TITLE
don't work in win11 24h2

### ISSUE THREAD

**Issue by hellangel2004** [apernet/hysteria#1222]
when I run "hysteria-windows-amd64.exe -c config.json" in win11 24h2  ,then get this error messages:"FATAL   failed to run SOCKS5 server     {"error": "invalid config: listen: listen tcp4 127.0.0.1:1080: bind: An attempt was made to access a socket in a way forbidden by its access permissions."}",but it work in win11 23H2 or win10, how to slove this problem?

**Comment by rvalitov** [comment]
Running as administrator does not solve the problem?

**Comment by hellangel2004** [comment]
NO
I already run it s as administrator ,but it doesn't work anyway

**Comment by dKenGuru** [comment]
System default uses BBR or Cubic?
Get-NetTCPSetting | Select SettingName, CongestionProvider in PowerShell

**Comment by haruue** [comment]
This seems to be a common problem on Windows that can be caused by various reasons. Please check the following links for more details:

https://stackoverflow.com/questions/10461257
https://stackoverflow.com/questions/4799651

There is nothing we can do on Hysteria to fix this. Using a different port should be the easiest way to solve the problem.
