### ISSUE TITLE
[Feature] Consider support auth forward

### ISSUE THREAD

**Issue by wenerme** [apernet/hysteria#671]
I want to expose the socks/http proxy in public env, this require hysteria client forward auth to server size.

Or maybe more than just forward auth, client need to dynamic create channel between server based one differen auth info ?

## Workaround

Server support expose socks or http proxy

## Context

This is not for gwf, but also for enterprise internal network access.

**Comment by haruue** [comment]
I think the more common use is to support multiple users of socks5/http inbound, rather than forwarding the sock5 auth credential to the hysteria server.

How about using v2ray between the hysteria client and your employee? It is a tool that supports socks5 as both inbound and outbound, as well as socks5 multiple users.

In other words, connect the outbound of v2ray to the socks5 inbound of the hysteria client, and you will be able to configure multiple user-password pairs on the socks5 inbound of v2ray.

**Comment by wenerme** [comment]
Found gost is more suited for my need https://github.com/go-gost/gost .

> support multiple users of socks5/http inbound

I found hysteria support http forword auth/external auth, I want to impl an api for hysteria auth, if client has the same ability, I thinks it's ok, but may lose some ability for future  user based config.

> How about using v2ray between the hysteria client and your employee

socks5 is not friendly for ios without any app preinstalled, ios support http proxy.
