### ISSUE TITLE
Cannot listen on local ipv6

### ISSUE THREAD

**Issue by AkramiPro** [apernet/hysteria#775]
#### i get error when want to listen on local ipv6

`listen: ::1:8585`
> FATAL   failed to load server config    {"error": "invalid config: listen: address ::1:8585: too many colons in address"}
---
#### but i can listen on local ipv4

`listen: 127.0.0.1:8585`
> INFO    server up and running
---
```
root@s01-2:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
```

**Comment by us254** [comment]
The IPv6 address needs to be enclosed in square brackets. This is because colons are used in IPv6 addresses, and a port number is separated by a colon. Without the brackets, it's unclear where the IPv6 address ends and where the port number begins.

You should change your configuration from `listen: ::1:8585` to `listen: [::1]:8585`.

This should resolve the error you're seeing.

**Comment by AkramiPro** [comment]
i tested before . not working

![image](https://github.com/apernet/hysteria/assets/54323929/e4e86fcd-c0b2-46c7-900a-a99a2adfd1a3)

![image](https://github.com/apernet/hysteria/assets/54323929/4b4bc7d7-1a1e-407d-9b6b-6654b232ed78)

**Comment by haruue** [comment]
```
yaml: did not find expected node content
```

This should be another problem in your config file, expect the one mentioned above.

Could you please post the full contents of your server config file (`/root/hysteria.1.yaml`) here so we can give you more help.

**Comment by AkramiPro** [comment]
i find the problem
to use ipv6 the hole value must be in double quotation like this :

`listen: "[::1]:40807"`
