### ISSUE TITLE
CentOS 7 中连接出现 {"error": "connect error: timeout: no recent network activity"} 问题

### ISSUE THREAD

**Issue by DreamFirstSnow** [apernet/hysteria#810]
已确认服务器444端口已放行并且可以通过外网进行访问
![{06A1F523-8478-4d3b-B4AF-250D56CEC294}](https://github.com/apernet/hysteria/assets/123160804/17c67395-444b-4567-a38e-ac3d67d4510c)
![{883F2405-7024-48cd-98F8-0ECD3F0748EA}](https://github.com/apernet/hysteria/assets/123160804/52390fc8-3fcb-4852-8c4d-8abdb1311fd4)

hysteria 正确运行了并且监听了该端口。
![{690FE596-E153-4dbd-8124-4290E9FEB565}](https://github.com/apernet/hysteria/assets/123160804/f4171583-1e4e-4d7b-8ad1-1d1ee1badeef)
![{3EE9CC32-30B6-49db-864E-31C321A59025}](https://github.com/apernet/hysteria/assets/123160804/9332b72a-f535-4a75-9f04-e06e70b2c13e)

配置文件如下
![{08857434-B55D-4079-A6DA-D00DD0A5F250}](https://github.com/apernet/hysteria/assets/123160804/ff921cad-0f9d-48f5-a180-f15647019115)
![{2665B07F-D1E7-4c2c-A371-513457C6B0CE}](https://github.com/apernet/hysteria/assets/123160804/c7bc56c0-0af8-4551-81e1-1d2f471b7a8d)

v2rayn已加载最新的 hysteria2 核心
![{6F7C703E-6F49-45b9-953B-D920B63EDE8F}](https://github.com/apernet/hysteria/assets/123160804/7e4b5b1f-1f2d-4f91-a586-346f6d72671e)
连接出现 {"error": "connect error: timeout: no recent network activity"} 问题
![{70F0764F-75B8-4fc8-AF82-281A24132153}](https://github.com/apernet/hysteria/assets/123160804/519fe8ae-970e-4cb2-9ed2-6aa99194a1ab)

执行 /usr/local/bin/hysteria server --config /etc/hysteria/config.yaml
![{24872749-D333-40a4-85BF-8C93AA896451}](https://github.com/apernet/hysteria/assets/123160804/2c92c993-faa1-4032-9f9f-804dea3e8727)

补充：
新发现！如果关闭了 hysteria 服务后执行 /usr/local/bin/hysteria server --config /etc/hysteria/config.yaml 显示正常？
![圖片](https://github.com/apernet/hysteria/assets/123160804/4dacca0f-3b23-4635-b6f0-279b140fa28f)

但是 v2rayn 依旧无法连接

**Comment by DreamFirstSnow** [comment]
> 为什么感觉是v2rayN的问题，和hysteria server应该没有关系吧

这个我也不确定，有空我试试clash

**Comment by hanlray** [comment]
遇到了同样问题 应该和v2rayN没关系 单独启动hy client也是这个错误

**Comment by DreamFirstSnow** [comment]
> 遇到了同样问题 应该和v2rayN没关系 单独启动hy client也是这个错误

据说centos7比较容易触发该问题，不知道是不是真的

**Comment by Phascolarctos** [comment]
客户端和服务端版本是不是不一致

**Comment by DreamFirstSnow** [comment]
> 客户端和服务端版本是不是不一致

已经手动替换客户端了啊

**Comment by 2602875449** [comment]
破案了，centos7的更新linux内核，这个搞了好久死活不行，更新完内核就正常了，因为我的另一个centos7 内核时5点几的，搭建是正常的
![图片](https://github.com/apernet/hysteria/assets/88760080/a7a93370-cdb8-4f04-b832-56a4eb88a914)
![uname](https://github.com/apernet/hysteria/assets/88760080/63ce02c5-eee9-45fa-aa7f-6fdc42d0b7a3)

**Comment by DreamFirstSnow** [comment]
> 破案了，centos7的更新linux内核，这个搞了好久死活不行，更新完内核就正常了，因为我的另一个centos7 内核是5点几的，搭建是正常的，可以尝试这个[更新Linux内核文章](https://blog.yywq.me/article/39f87fd6-1c3e-4826-90d9-5d031393ca8d) ![图片](https://user-images.githubusercontent.com/88760080/282406850-a7a93370-cdb8-4f04-b832-56a4eb88a914.png) ![uname](https://user-images.githubusercontent.com/88760080/282406874-63ce02c5-eee9-45fa-aa7f-6fdc42d0b7a3.png)

所以真的是系统问题啊，hhh

**Comment by yaochong-06** [comment]
一样的问题，udp端口都通，centos内核也升级了
服务器端：
[root@kabirgoyal ~]# netstat -ntplu
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
... ...       
udp6       0      0 :::30040                :::*                                1208/./hysteria-lin 

服务器是centos7，版本如下
[root@kabirgoyal yc]# uname -a 
Linux kabirgoyal.com 6.7.6-1.el7.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Feb 23 17:06:52 EST 2024 x86_64 x86_64 x86_64 GNU/Linux
[root@kabirgoyal yc]# uname -r 
6.7.6-1.el7.elrepo.x86_64


[root@kabirgoyal yc]# cat server.yaml 
listen: :30040

tls:
  cert: "./cert.pem"
  key: "./key.pem"

bandwidth:
  up: 100 mbps
  down: 20 mbps

auth:
  type: password
  password: chika

resolver:
  type: https
  https:
    addr: 1.1.1.1:443
    timeout: 10s


[root@kabirgoyal yc]# cat startserver.log 
2024-02-28T11:39:42Z    INFO    server mode
2024-02-28T11:39:42Z    INFO    server up and running   {"listen": ":30040"}


服务器的ip地址是209.141.55.218，我hysteria程序启用的端口是30040，并且防火墙的状态如下
[root@kabirgoyal ~]# systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Wed 2024-02-28 11:40:52 UTC; 12min ago
     Docs: man:firewalld(1)
  Process: 538 ExecStart=/usr/sbin/firewalld --nofork --nopid $FIREWALLD_ARGS (code=exited, status=0/SUCCESS)
 Main PID: 538 (code=exited, status=0/SUCCESS)

Feb 28 11:38:42 localhost.localdomain systemd[1]: Starting firewalld - dynamic firewall daemon...
Feb 28 11:38:43 localhost.localdomain systemd[1]: Started firewalld - dynamic firewall daemon.
Feb 28 11:38:43 localhost.localdomain firewalld[538]: WARNING: AllowZoneDrifting is enabled. This is considered an inse... now.
Feb 28 11:38:43 localhost.localdomain firewalld[538]: ERROR: Failed to read file "/proc/sys/net/netfilter/nf_conntrack_...lper'
Feb 28 11:38:43 localhost.localdomain firewalld[538]: WARNING: Failed to get and parse nf_conntrack_helper setting
Feb 28 11:40:50 kabirgoyal.com systemd[1]: Stopping firewalld - dynamic firewall daemon...
Feb 28 11:40:52 kabirgoyal.com systemd[1]: Stopped firewalld - dynamic firewall daemon.
Hint: Some lines were ellipsized, use -l to show in full.

端口也都通的
客户端发送：
echo "Test UDP message" | nc -u 209.141.55.218 30041

服务器：
[root@kabirgoyal yc]# nc -u -l 30040
Ncat: bind to :::30040: Address already in use. QUITTING.
[root@kabirgoyal yc]# nc -u -l 30041
Test UDP message

**Comment by chengxuylongweiguo** [comment]
> 客户端和服务端版本是不是不一致
要在运营商的控制端放行UDP协议的端口，而不是TCP端口

**Comment by Airskotex** [comment]
https://blog.yywq.me/article/39f87fd6-1c3e-4826-90d9-5d031393ca8d
这个打不开
blog.yywq.me currently does not have any sponsors for you.

**Comment by Airskotex** [comment]
> > 破案了，centos7的更新linux内核，这个搞了好久死活不行，更新完内核就正常了，因为我的另一个centos7 内核是5点几的，搭建是正常的，可以尝试这个[更新Linux内核文章](https://blog.yywq.me/article/39f87fd6-1c3e-4826-90d9-5d031393ca8d) ![图片](https://user-images.githubusercontent.com/88760080/282406850-a7a93370-cdb8-4f04-b832-56a4eb88a914.png) ![uname](https://user-images.githubusercontent.com/88760080/282406874-63ce02c5-eee9-45fa-aa7f-6fdc42d0b7a3.png)
> 
> 所以真的是系统问题啊，hhh

https://blog.yywq.me/article/39f87fd6-1c3e-4826-90d9-5d031393ca8d
这个打不开
blog.yywq.me currently does not have any sponsors for you.

**Comment by hbqclh** [comment]
各位大佬，我用的是arm的openwrt，里面跑的。经测试，hy.yml文件运行正常（自定义的文件）。UDP.json就一直是这样的报错（该文件由passwall生成）。能看出是哪里的问题吗？
![Image](https://github.com/user-attachments/assets/b3710538-3d2b-4293-a381-8ff1a38a3448)
